version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/cleaningdb
      - MONGO_USER=
      - MONGO_PASS=
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: cleaningdb
    volumes:
      - mongo_data:/data/db
    command: 
      [--noauth]

volumes:
  mongo_data: