version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cleaning-app
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./cleaning-app-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/cleaning-app?authSource=admin
      - NODE_ENV=production

volumes:
  mongo_data: